name:                smallScheme
version:             0.1.0.0
github:              "githubuser/smallScheme"
license:             BSD3
author:              "Richard Yu"
maintainer:          "richardyu042@gmail.com"
copyright:           "2021 Richard Yu"

extra-source-files:
- README.md
- ChangeLog.md
- src/Lexer.x

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/smallScheme#readme>

dependencies:
- base >= 4.7 && < 5
- parsec
- transformers
- mtl
- hashable
- filepath
# array needed for alex
- array

library:
  source-dirs: src

executables:
  smallScheme-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - smallScheme

tests:
  smallScheme-test:
    main:                Regression.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - smallScheme
    - tasty
    - tasty-hunit
    - tasty-golden
    - process
    - directory
    - turtle
